### ISSUE TITLE
フレームワークの再選定の是非について

### ISSUE THREAD

**Issue by func-hs** [kcis/kcis#3]
# はじめに

フレームワークを見つめなおす必要があると聞いて。確かにMVCやそれらに関するドキュメントが1箇所に固まってるのはいいことだし、可能な限りそうなるように努力する必要があります。
# 前提条件

まず、どのフレームワークを選ぶにしても、以下の事はまず前提として記憶しておく必要があると思います。
## 必要な機能

データベースとページ部品間とでデータのIOのみを行う(そこから先の複雑な計算をコンピュータが必要としない)ようなシステムの場合、モデルやコントローラを多機能なものにしなくても
- ルータ
- コントローラ(あくまでURLアクセスに対して遷移先を決定する程度のごく単純なものでOK)
- ビュー
- データベースへ直接アクセスを行うAPI、及び、構造体やクラスもしくはそれに近いデータ構造(データベースとやり取りするデータを一時的に保存するのに使う)

があれば実装しきれる場合が多いです。現KCISの機能は、グラフチャートやカレンダーの出力こそ必要となるものの、前者はウェブフレームワークとは別なツールが必要になるだろうし、後者はほとんどCSSやJavaScriptの領域なため、MVC間がやるのはあくまで単純なデータの送受信に留まると思います。
## 単純なデータ入出力より複雑な処理は存在しないか

フレームワークや開発に利用する言語を丸ごと入れなおすという場合、データを単純に入出力するということよりも複雑な処理を、そのフレームワークや言語がどこまでカバーできるかをよく考える必要があります。
## 気持ちや感覚的な事(哲学的ともいう)は後で

意義があるかどうかは、一通り作ってしまった後で考えればよいと思います。
今からそれを考えだしてしまうと、そこで行き詰まってしまうことが多いからです。
(自分の人生の意味や意義を今考えても仕方ないのと同じ)
# 雑感

私としては、今の仕様の範囲では、あまり多機能なフレームワークは必要ないかなぁというのが正直なところです。**スキャフォールド**や**高機能なリクエスト・レスポンスハンドリング**が必要になるかは疑問。
PHPやRubyは、フレームワークの機能範囲よりも言語仕様との闘いになるような…？

また、本格的な再選定への議論や検討は、 @master-q さんが中国へ渡ったあと、出張先の職場でも同様に行われるような気がします。

これらを踏まえた上で、今週中(できれば2/19まで)に話しあいましょう :)

P.S.: 私としては Play+Scala でも全然平気ですよ！

**Comment by master-q** [comment]
うーん。ぼくの今あるScala+Playへの雑感はSlickとplay2-authの間にみられるようなフレームワークとしての不整合です。デファクトとしてのモデルがないために、フレームワーク全体に不整合があるんではないか？と推測しています。。。

**Comment by master-q** [comment]
”意義があるかどうか" というのは、"二週間で一旦見切りをつけるか、一ヶ月で見切りをつけるか"という工数の投資について発言したつもりでした。

**Comment by master-q** [comment]
> スキャフォールドや高機能なリクエスト・レスポンスハンドリングが必要になるかは疑問

ここは完全に同意します。

**Comment by master-q** [comment]
あとはどのフレームワークを選定するにしても、カレンダーのような機能を作り込むにはその言語を使用可能でなければならない、という視点もあると思います。
このような作り込みは今回の案件では少ないだろう、とみつもっていたのですが、いまの認証に関してさえScala+Playでは作り込みが必要になりました。
もちろんこれPlayが悪いのではありません。しかし、1週間勉強したかぎりでは僕には今のplay2-authとslickの問題に歯がたちませんでした。 @func-hs さんはこのような作り込みに戦力になれると思いますが、僕の力では今のところ有意な作り込みを行なえていません。

この学習曲線があと2.5週間後に追い付くのか、それとも追い付かないのか、は早めに知りたいのです。

**Comment by master-q** [comment]
カレンダーは実はMVCが密接に関連するアプリケーションの例ではないでしょうか？

**Comment by master-q** [comment]
グラフはたしかに一度表示すれば良いのであまりモデルモデルしたものは不要だと思います。

**Comment by func-hs** [comment]
> カレンダーは実は MVC が密接に関連するアプリケーションの例ではないでしょうか？

MVC を要することは確かです。しかし、カレンダーに関しては MVC そのものよりも、 CSS や  JavaScript といった、 **MVC に付随する**モジュールによって、カレンダー表全体を(あくまでユーザにとって)どこまでストレスを感じにくいデザイン&実装にできるのかの方が大事な気がしています。現行のものを見てみても、完成度は置いておいても Google カレンダーの使い心地を参考にしているように見えます。

私は契約上、3月上旬で居なくなる予定ですが、 @master-q さんはこの後中国への出張が待っています。その出張先で現状の構成に対する評価や、そもそもこのまま使い続けるのかどうかすらわからない、もしかするとScalaもPlayも使わなくなるかもしれない、というのを考えると、今の内から環境構成を深く考え込んでいてもどうしようもない気がします。

> あとはどのフレームワークを選定するにしても、カレンダーのような機能を作り込むにはその言語を使用可能でなければならない、という視点もあると思います。このような作り込みは今回の案件では少ないだろう、とみつもっていたのですが、いまの認証に関してさえScala+Playでは作り込みが必要になりました。

おそらく、ログインの認証に関する API が標準でライブラリに組み込まれていて、そこそこストレスない感じに使えるようなものは PHP しかないでしょう。その PHP も、ライブラリこそ豊富なものの、型システムは脆弱で、当案件のように、数値をプロットするとか、そういう中のデータの形を統一したい部分では、ゴミが混ざってもそれを感知する手段に乏しいのが現状です。
なので、ライブラリが豊富であり、かつ、型システムも必要十分程度にしっかりしているものとなると、次点では **Java** ということになります。今では Scala という静的型かつ Java よりも強力な言語機能を備えた onJVM な言語があり、おそらくこの先の事を考えると、これによらざるを得ない気がします。
Haskell/yesod にするにしても、 Ruby/Rails にするにしても、コアが小さい言語での開発は追加で必要になるパッケージとの依存関係とも戦う必要が出てきますし、Haskell に至っては言語仕様を正確に把握・利用できる技術者がどれだけ要るのかも問題になってきます。

> この学習曲線があと2.5週間後に追い付くのか、それとも追い付かないのか、は早めに知りたいのです。

同意します。1ヶ月というごく短期間では私も必要十分に理解できるかどうかは怪しいです。しかし、途中から言語やフレームワークを変えると、その短期間でどうにか貯めこんできた知識を一度放して、新しい言語やフレームワークに対応するために、再度**早くても**1〜5日程度学習する時間を要してしまい、その分納期までの猶予が喪失してしまいます。もっと言うと、選びなおすことにも時間を取られるでしょう。当案件が今後まだまだ(少なくとも3ヶ月は)続くなら、選びなおしても間に合うと思いますが、現状では、この案件が未来でどう扱われていくのかが見えておらず、また納期にもほとんど余裕がないのでその都度納期の猶予がなくなっていきます…(´･_･`)

_本音を言うと、私がこの1ヶ月より後に御社にどう扱われるのかが全く見えてこないので、私としては納期までに間に合うように動きたいのです XD_

ただし、もし @master-q さんが言語やフレームワークを総入れ替えして、この1ヶ月間ないし中国に渡ってからの1ヶ月間(もしかして、もっと長い？)の間に対応しきれるのであれば、私は追従します :)

**Comment by master-q** [comment]
> 本音を言うと、私がこの1ヶ月より後に御社にどう扱われるのかが全く見えてこないので、私としては納期までに間に合うように動きたいのです XD

ここだけ先に反応します。
「いきなり長期に高額の金額で契約するのはむづかしい」
と黒岩さんに返答をもらって今回の契約になっています。
一ヶ月より後に関しては、、、ぼくもどうなるかは今KCISさんとの打ち合わせのゆくえ次第です。

**Comment by func-hs** [comment]
なるほど。。。

**Comment by master-q** [comment]
それから今月作るプロトタイプが実際に運用されることは **絶対にありません** 。岡部の立てた (まだKCISさんの了承がおりていない) 計画では、この一ヶ月の間にフレームワークの選定が間違っていないか、作るのに必要な技術はたりているか、などの試験をする予定でした。

**Comment by master-q** [comment]
もうちょっと言うと、この一ヶ月より先ではフレームワークを選定しなおすことは大変困難であろう、というのが当初の見積りでした。

**Comment by func-hs** [comment]
うぅむ。となると、私に課された以下の5つの機能:
- ログイン画面
- 利用者一覧
- バイタル管理
- カレンダー
- スマフォ向けHTML5デザイン(デザイナの案が来るのが先だけども)

の納期的な部分はどうなるのでしょう。書類上では「仕事が成ってなかったら給料減額な！」となっているのですが、そもそも5件とも完成しなくてよいという前提でしたっけ？

**Comment by master-q** [comment]
たしかに一ヶ月のScala+Playの試験の後に、 **再度** Yesodに対する試験を一ヶ月行なうことは可能だと思います。ただ、、、主観的な感想ですが、プロトタイプに二ヶ月を要するのは微温いと感じて、二週間で結論を出してしまおうとしていました。

**Comment by master-q** [comment]
> 書類上では「仕事が成ってなかったら給料減額な！」となっているのですが、そもそも5件とも完成しなくてよいという前提でしたっけ？

あーそんな文言が入っていたのか。。。

**Comment by master-q** [comment]
そこに関しては黒岩さん相談だと思います。
「フレームワークの感触が悪いので、別の作業とのかねあいで未達が発生します」
と言うことはできると考えていました。

(黒岩さんの意見を聞いていないので100％の自信はありません)

**Comment by func-hs** [comment]
> 二週間で結論を出してしまおうとしていました。

最後まで現行のものと同じままにしか進めなくてよいのであれば、それでも大丈夫な気はします。
ただし、作り直し案件として持ち込まれているということは、将来的にシステムの適用規模が拡大しうるので、二週間でフレームワークやら外部的な部分を決めて上手くいかせる自信はないですね…(´･_･`)

**Comment by master-q** [comment]
で、ちょっと帰ってきて、 @func-hs さんの投稿を見て、「それでも一ヶ月、Scala+Playに費やすのも良いかな」と今は感じています。それでも、先の目標は満額達成は二人でやったとしてもむづかしいと感じています。

**Comment by func-hs** [comment]
> そこに関しては黒岩さん相談だと思います。「フレームワークの感触が悪いので、別の作業とのかねあいで未達が発生します」と言うことはできると考えていました。黒岩さんの意見を聞いていないので100％の自信はありません

なんてこったいｗｗｗクッソワロタｗｗｗワロタ…(´･_･`)
どの道私の方にはもとから十分な猶予がないので、変えるにしても2/19 の夕方までにはどうにか決めちゃいたい。

**Comment by func-hs** [comment]
> 先の目標は満額達成は二人でやったとしてもむづかしいと感じています。

なるほどなぁ…(´･_･`)

**Comment by master-q** [comment]
ほんとうにやりたいことは「一ヶ月はPlayを評価して、もう一ヶ月は(たぶんYesod)を評価したい」ということだから、それを正直に黒岩さんに言った方がいいのかもな。。。
それから今回のプロトタイプで未達が発生しそうな感触なことも言っておいた方がいいと思いました。

こーゆーのは早めに言った方が良いのです。

**Comment by func-hs** [comment]
それは同意します。
では、明日(今日？)の昼あたりにその旨報告する形にしますか？

**Comment by master-q** [comment]
今メール書いています。。。

**Comment by func-hs** [comment]
アッハイ

**Comment by master-q** [comment]
@func-hs さんから言う形にした方がいいのかな。。。

**Comment by master-q** [comment]
うーん。たぶん僕からの方がいいんだと思う。作文します。

**Comment by func-hs** [comment]
了解です。

**Comment by master-q** [comment]
あとログインはYesodだともっと楽だと思う。。。

**Comment by master-q** [comment]
Yesodがまずいのは、ライブラリバージョンの非互換やミスマッチが多いことかな。。。

**Comment by master-q** [comment]
とりあえず今月満額で達成できそうにないことは言っておかないといけない。

**Comment by func-hs** [comment]
忍びないなぁ…(´･_･`)

**Comment by func-hs** [comment]
後なんか今日はやたらと Yesod が Build failed してる issue が飛ぶｗ

**Comment by master-q** [comment]
いや、見積りがアマかった。

**Comment by master-q** [comment]
見積もりが倍間違ってたな。。。

**Comment by func-hs** [comment]
ｽﾏﾋｮｻｲﾖ以外の4つなら、1ヶ月でやりきれないこともないかなぁという印象ではあるんだけどねぇ

**Comment by master-q** [comment]
カレンダーいける？

**Comment by master-q** [comment]
https://github.com/biesior/Play-20-Sample-FullCalendar-Java これしかないよ。。。

**Comment by func-hs** [comment]
Playでなくとも、 Google カレンダー に関して車輪の再発明をしたがる人自体がそう居るものではないと思う…(´･_･`)

**Comment by master-q** [comment]
そうそう。。。Build failばっかりだから、バージョンを全部指定してcabal-devなりの環境を作る何かを作らなきゃだよな。。。

**Comment by func-hs** [comment]
そうなんだなぁ(´･_･`)

**Comment by master-q** [comment]
ま、そういう意味もあって、2ヶ月フレームワーク選定とプロトタイピングに使わせてもらえるなら、ばんばんざいかなぁと。

**Comment by func-hs** [comment]
土日を潰して他の2つを終わらせて、残りの二週間でぎりかなぁって印象

**Comment by master-q** [comment]
土日を入れてはいけなかった。。。 #orz

**Comment by func-hs** [comment]
なるほど。ということは契約書の書き直し&再発行とかもお願いした方がいいのかなぁ＞俺

**Comment by master-q** [comment]
それは先方にまかせればいいと思う。 < 書き直し

**Comment by func-hs** [comment]
ふむふむ

**Comment by func-hs** [comment]
ちなみにｽﾏﾋｮの方は、「まず何より先にデザイナを見つけて有り難いご意見を頂いてきてください」としか言いようがないなぁ(´･_･`)

**Comment by master-q** [comment]
- カレンダー
- スマフォ向けHTML5デザイン(デザイナの案が来るのが先だけども)

この2つは除くということにしたいなぁ。

**Comment by func-hs** [comment]
色んな問題と向き合わないといけないからなぁ…
最低でも2ヶ月は期間欲しかったかも

**Comment by master-q** [comment]
みつもりが倍まちがえていた。。。 #orz

**Comment by func-hs** [comment]
うーん…なんというか…減額される可能性が高い上に、1ヶ月後も仕事が続けられるかどうかも見えないのであれば、このままやりきってしまうのもありに思える…

**Comment by master-q** [comment]
こんなメール書いているけどやめとく？

```
岡部です。いつもお世話になっております。

今日で新システムのプロトタイピングについて1.5週間を
費やしたところです。

Scala+Playの組み合わせによるフレームワークを使用して
きたのですが、思ったより開発効率があがりません。
原因はいくつかありますが、岡部の視点ではMVCのモデル
部分にデファクトスタンダードな部品が不在のために、
フレームワーク内でソフトウェア部品の不整合が発生
していることです。

この不整合の良い例がログイン画面の設計で、今悩んで
いる範囲だと以下2つのライブラリが簡単には同時並用
できません。

https://github.com/playframework/play-slick
https://github.com/t2v/play2-auth

そこで、今回Scala+Playを使ったプロトタイピングについて
以下2つを提案させていただけないでしょうか。


## 1. 以下2つを一ヶ月のプロトタイプ作成の範囲から取り除く

* カレンダー
* スマフォ向けHTML5デザイン

## 2. Haskell+Yesodを使ったプロトタイピングにもう一ヶ月使う

松舘と岡部はScala言語には疎いのですが、Haskell言語に関しては
通常通り読み書きできます。つまりチームの中では共通言語
であるわけです。

開発効率が得られるか


松舘さんの工数を来月以降も使わせていただけるのであれば、
このような計画もうまく行くと思います。

よろしくお願いします。
-- 
Kiwamu Okabe at METASEPI DESIGN
```

**Comment by func-hs** [comment]
概ね同意ではあるんだけど、Haskellかぁ。キホンのキはわかってるけど、THは未だによくわかってないし、なんか実運用するには躊躇うなぁ…。無難にCakePHPにしとくのもありかもしれない。

**Comment by master-q** [comment]
なるほど。。。単純にHaskellに対する不安がある、ということですね。。。THは混乱の元だけど、まぁあーゆーものです。。。

**Comment by func-hs** [comment]
「これ！」と言い切らずに、「もう一度最初から選びなおすからそのための時間として1ヶ月くれ」の方がいいかも？

**Comment by master-q** [comment]
```
岡部です。いつもお世話になっております。

今日で新システムのプロトタイピングについて1.5週間を
費やしたところです。

Scala+Playの組み合わせによるフレームワークを使用して
きたのですが、思ったより開発効率があがりません。
原因はいくつかありますが、岡部の視点ではMVCのモデル
部分にデファクトスタンダードな部品が不在のために、
フレームワーク内でソフトウェア部品の不整合が発生
していることです。

この不整合の良い例がログイン画面の設計で、今悩んで
いる範囲だと以下2つのライブラリが簡単には同時並用
できません。

https://github.com/playframework/play-slick
https://github.com/t2v/play2-auth

そこで、今回Scala+Playを使ったプロトタイピングについて
以下2つを提案させていただけないでしょうか。


## 1. 以下2つを一ヶ月のプロトタイプ作成の範囲から取り除く

* カレンダー
* スマフォ向けHTML5デザイン

当初岡部が見積った工数が倍程度異なったようです。

## 2. 別のフレームワークを使ったプロトタイピングにもう一ヶ月使う

別のフレームワークを使えば開発効率が得られるかどうか、
どうしても本番開発の前に試してみたいのです。
実際の開発がはじまってしまったら、フレームワークを選定しなおす
ことは完全に不可能になってしまいます。

松舘さんの工数を来月以降も使わせていただけるのであれば、
このような計画もうまく行くと思います。

よろしくお願いします。
-- 
Kiwamu Okabe at METASEPI DESIGN
```

**Comment by master-q** [comment]
明日までこのメール寝かせて、から送信しようと思います。

**Comment by func-hs** [comment]
うん。大丈夫そう。

**Comment by func-hs** [comment]
> 明日までこのメール寝かせて、から送信しようと思います。

ですね。岡部さんも寝てるだろうし、このメールも俺達も一旦寝ましょう :-)

**Comment by master-q** [comment]
なげちゃった。

**Comment by func-hs** [comment]
はやｗ
